import { legalValue } from './legal-config.js';
const escape = value => String(value || '').replace(/[&<>"']/g, char => ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[char]));
export function page(title, body) {
  return `<!doctype html><html lang="fr"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="robots" content="noindex,nofollow"><meta name="description" content="${escape(title)} — Mon emploi du temps INSPÉ"><title>${escape(title)} · Mon emploi du temps</title><link rel="stylesheet" href="/pages.css"></head><body><main><a href="/">← Mon emploi du temps</a><h1>${escape(title)}</h1>${body}</main><footer><a href="/mentions-legales">Mentions légales</a><a href="/confidentialite">Confidentialité</a></footer></body></html>`;
}
export function legalPage() {
  const publisher=escape(legalValue('LEGAL_PUBLISHER') || 'Birost Web');
  const address=escape(legalValue('LEGAL_ADDRESS') || 'À compléter avant publication');
  const contact=escape(legalValue('LEGAL_CONTACT') || 'À compléter avant publication');
  const status=escape(legalValue('LEGAL_STATUS') || 'Statut à préciser');
  return page('Mentions légales', `<h2>Éditeur</h2><p>${publisher}<br>${status}<br>${address}<br>Contact : ${contact}</p><h2>Identification de l’entreprise</h2><p>Immatriculation : ${escape(legalValue('LEGAL_REGISTRATION') || "À compléter")}<br>TVA : ${escape(legalValue('LEGAL_VAT') || "À préciser selon régime")}<br>Capital social : ${escape(legalValue('LEGAL_CAPITAL') || "À préciser si applicable")}</p><h2>Direction de la publication</h2><p>${escape(legalValue('LEGAL_DIRECTOR') || publisher)}</p><h2>Hébergement</h2><p>OVH SAS — 2 rue Kellermann, 59100 Roubaix, France.<br>Téléphone : 1007 (France).<br>Infrastructure hébergée sur un VPS OVH, administrée par l’éditeur avec Dokploy.</p><h2>Crédits et licences</h2><p>Police DM Sans, © The DM Sans Project Authors, licence SIL Open Font License 1.1 (distribuée via Fontsource). Icônes Lucide, © Lucide Icons and Contributors, licence ISC. L’application utilise aussi Vue (MIT) et d’autres bibliothèques open source sous licences MIT, BSD ou Apache 2.0.</p><h2>À propos du service</h2><p>Cette application est destinée aux membres de la promotion INSPÉ de l’éditeur. Elle permet de consulter localement un export XML CELCAT choisi par l’utilisateur, sans transmettre d’identifiants universitaires. Elle n’est pas un service officiel de l’université. Les informations du service universitaire font référence.</p><h2>Contact et droits</h2><p>Pour signaler une erreur ou exercer vos droits, utilisez le contact de l’éditeur ci-dessus. Consultez la <a href="/confidentialite">politique de confidentialité</a>.</p>`);
}
export function privacyPage() {
  return page('Politique de confidentialité', `<h2>Responsable et contact</h2><p>${escape(legalValue('LEGAL_PUBLISHER') || 'Birost Web')}. Contact : ${escape(legalValue('LEGAL_CONTACT') || 'À renseigner avant publication')}.</p><h2>Planning local</h2><p>Le fichier XML CELCAT est choisi par l’utilisateur et lu uniquement en mémoire dans son navigateur. Il n’est envoyé à aucun serveur, ni enregistré dans une base ou le stockage local. Fermer ou recharger la page efface le planning. L’application ne collecte ni identifiant ni mot de passe universitaire, ne dépose aucun cookie de session et ne contacte pas CAS/CELCAT.</p><p>Un export de groupe peut contenir des informations sur des enseignants ou d’autres personnes : ne le publiez pas et ne le partagez pas. Les champs enseignants, équipes et notes sont retirés du résultat affiché ; le fichier source reste uniquement sur votre appareil.</p><h2>Données techniques et finalités</h2><p>Le serveur reçoit uniquement les requêtes de chargement du site (adresse IP, date, ressource demandée), nécessaires à la fourniture et à la sécurité du service, sur la base de l’intérêt légitime de l’éditeur. Les journaux techniques applicatifs ne contiennent aucun planning. La durée de conservation retenue pour les journaux applicatifs et d’infrastructure est de ${escape(legalValue('LOG_RETENTION_DAYS') || 'durée à configurer')} jours ; leur suppression automatique à cette échéance sera configurée et vérifiée par l’éditeur, qui administre le serveur, avant la mise en ligne. Aucun usage publicitaire ni mesure d’audience n’est intégré.</p><h2>Stockage local</h2><p>Seule la préférence d’apparence edt-theme-v2 peut rester dans le stockage local jusqu’à sa suppression. Elle est nécessaire à la préférence demandée ; aucun traceur soumis au consentement n’est intégré. Le navigateur ne contacte que le domaine de l’application (aucun CDN, service de mesure d’audience ou police externe).</p><h2>Destinataires et hébergement</h2><p>Les données techniques sont traitées par l’éditeur et son hébergeur OVH (VPS situé en France, selon la configuration indiquée par l’éditeur). Tout ajout de prestataire ou transfert hors de l’Union européenne devra être évalué et décrit dans cette politique.</p><h2>Vos droits</h2><p>Vous pouvez demander l’accès, la rectification, l’effacement, la limitation et l’opposition en contactant l’éditeur. Les données universitaires à la source doivent être rectifiées auprès de l’université. Vous pouvez également adresser une réclamation à la <a href="https://www.cnil.fr/fr/plaintes" rel="noreferrer">CNIL</a>.</p>`);
}
